info:
  contact: {}
  description: GoTravelApplication前后端分离后端API.
  title: travel项目api
  version: "1.0"
paths:
  /ping/demo:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            type: string
      tags:
      - ping Demo
swagger: "2.0"
