info:
  contact: {}
  description: GoTravelApplication前后端分离后端API.
  title: travel项目api
  version: "1.0"
paths:
  /ping/demo:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            type: string
      tags:
      - ping Demo
  /user/getUserInfo:
    get:
      description: Get user by ID
      operationId: get-user-by-id
      parameters:
      - description: User ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            type: string
      summary: Get user by ID
      tags:
      - 用户中心
swagger: "2.0"
